#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: HelmRelease
metadata:
  name: cert-manager
  labels:
    chart_group: cert-manager
spec:
  releaseName: cm-cert-manager
  chart:
    spec:
      chart: cert-manager
      version: v1.7.1
      sourceRef:
        kind: HelmRepository
        name: stx-platform
  interval: 5m
  timeout: 30m
  test:
    enable: false
  install:
    disableHooks: false
  upgrade:
    disableHooks: false
    force: true
  valuesFrom:
    - kind: Secret
      name: cert-manager-static-overrides
      valuesKey: cert-manager-static-overrides.yaml
    - kind: Secret
      name: cert-manager-system-overrides
      valuesKey: cert-manager-system-overrides.yaml
---
apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: HelmRelease
metadata:
  name: cert-manager-psp-rolebinding
  labels:
    chart_group: cert-manager-psp-rolebinding
spec:
  releaseName: cm-cert-manager-psp-rolebinding
  chart:
    spec:
      chart: psp-rolebinding
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: stx-platform
  interval: 5m
  timeout: 30m
  test:
    enable: false
  install:
    disableHooks: false
  upgrade:
    force: true
