#!/bin/bash
set -x

PKG_BUILD_NAME=$1
PKG_BUILD_ROOT=$(realpath `pwd`/${PKG_BUILD_NAME})
PKG_DIR="cert-manager-helm"
STX_BASE=$(realpath ${MY_REPO}/stx)
SRC=$(realpath ${STX_BASE}/cert-manager-armada-app/${PKG_DIR})

mkdir -p ${PKG_BUILD_ROOT}
pushd ${PKG_BUILD_ROOT}

# Local mirror workaround until CGCS_BASE mirror is supported.
STX_MIRROR=$(realpath "/import/mirrors/starlingx")

# Download certmanager helm source package.
CERT_MGR_PKG="helm-charts-certmanager-1d6ecc9cf8d841782acb5f3d3c28467c24c5fd18.tar.gz"
CERT_MGR_SRC_PATH=$(realpath ${STX_MIRROR}/downloads/${CERT_MGR_PKG})
cp ${CERT_MGR_SRC_PATH} ${PKG_BUILD_ROOT}

# Extract the certmanager tar file.
tar xfz ${CERT_MGR_PKG}

# Copy source files to the build directory.
cp -pr ${SRC}/files/* ${PKG_BUILD_ROOT}
