#
# Copyright (c) 2022-2023 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: HelmRelease
metadata:
  name: cert-manager
  labels:
    chart_group: cert-manager
spec:
  releaseName: cm-cert-manager
  chart:
    spec:
      chart: cert-manager
      version: REPLACE_HELM_CHART_VERSION
      sourceRef:
        kind: HelmRepository
        name: stx-platform
  interval: 1m
  timeout: 30m
  test:
    enable: false
  install:
    disableHooks: false
  upgrade:
    disableHooks: false
    force: true
  valuesFrom:
    - kind: Secret
      name: cert-manager-static-overrides
      valuesKey: cert-manager-static-overrides.yaml
    - kind: Secret
      name: cert-manager-system-overrides
      valuesKey: cert-manager-system-overrides.yaml
