---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: certmgr-crds
data:
  chart_name: certmgr-crds
  release: certmgr-crds
  namespace: cert-manager
  wait:
    timeout: 60
    resources: []
  values:
    nodeSelector:
      node-role.kubernetes.io/master: ""
  source:
    type: tar
    location: http://172.17.0.1:8080/helm_charts/stx-platform/certmgr-crds-0.1.0.tgz
    subpath: certmgr-crds
    reference: master
  dependencies: []
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: cert-manager
data:
  chart_name: cert-manager
  release: cert-manager
  namespace: cert-manager
  wait:
    timeout: 300
    labels:
      app: cert-manager
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
            app: cert-manager
  values:
    global:
      imagePullSecrets: [{"name": "default-registry-key"}]
    image:
      repository: quay.io/jetstack/cert-manager-controller
      tag: v0.14.0
    nodeSelector:
      node-role.kubernetes.io/master: ""
    webhook:
      image:
        repository: quay.io/jetstack/cert-manager-webhook
        tag: v0.14.0
      nodeSelector:
        node-role.kubernetes.io/master: ""
    cainjector:
      image:
        repository: quay.io/jetstack/cert-manager-cainjector
        tag: v0.14.0
      nodeSelector:
        node-role.kubernetes.io/master: ""
  source:
    type: tar
    location: http://172.17.0.1/helm_charts/stx-platform/cert-manager-v0.1.0.tgz
    subpath: cert-manager
    reference: master
  dependencies: []
---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: cert-manager
data:
  description: "StarlingX Cert-Manager"
  sequenced: true
  chart_group:
    - certmgr-crds
    - cert-manager
---
schema: armada/Manifest/v1
metadata:
  schema: metadata/Document/v1
  name: cert-manager-manifest
data:
  release_prefix: cm
  chart_groups:
    - cert-manager
